baseurl = "https://www.bio.ics.saitama-u.ac.jp"
title = "埼玉大学松永研究室"
languageCode = "ja-jp"
paginate = "1" # Number of posts per page
theme = "mainroad"
disqusShortname = "" # Enable Disqus comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id

hasCJKLanguage = true # 日本語・中国語・韓国語の単語カウントを有効にする
summaryLength = 120 # サマリーの長さを120単語にする


[Author] # Used in authorbox
  name = "Yasuhiro Matsunaga"
  bio = ""
  avatar = "img/avatar.png"

[Params]
  subtitle = "" # Deprecated in favor of .Site.Params.logo.subtitle
  description = "Website of Matsuanga-lab Saitama University" # Site description. Used in meta description
  copyright = "Yasuhiro Matsunaga" # Footer copyright holder, otherwise will use site title
  opengraph = true # Enable OpenGraph if true
  schema = true # Enable Schema
  twitter_cards = true # Enable Twitter Cards if true
  readmore = false # Show "Read more" button in list if true
  authorbox = true # Show authorbox at bottom of pages if true
  toc = false # Enable Table of Contents
  pager = false # Show pager navigation (prev/next links) at the bottom of pages if true
  post_meta = ["author", "date", "categories", "translations"] # Order of post meta information
  mainSections = ["post", "blog", "news"] # Specify section pages to show on home page and the "Recent articles" widget
  dateformat = "2006-01-02" # Change the format of dates
  mathjax = true # Enable MathJax
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path
  mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
  googleFontsLink = "https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700" # Load Google Fonts
  highlightColor = "" # Deprecated in favor of .Site.Params.style.vars.highlightColor
  customCSS = ["css/custom.css"] # Include custom CSS files
  customJS = ["js/custom.js"] # Include custom JS files

[Params.style.vars]
  #highlightColor = "#e22d30" # Override highlight color
  #highlightColor = "#ff9aa2" # Override highlight color
  #highlightColor = "#177abe" # Override highlight color
  highlightColor = "#d60435" # Override highlight color

  # Override font-family sets. Secondary font-family set responsible for pre, code, kbd, and samp tags font
  # Take care of different quotes OR escaping symbols in these params if necessary
  fontFamilyPrimary = "'Open Sans', Helvetica, Arial, sans-serif"
  fontFamilySecondary = "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"

[Params.logo]
  #image = "img/placeholder.png" # Logo image. Path relative to "static"
  image = "AdK.png" # Logo image. Path relative to "static"
  title = "埼玉大学松永研究室" # Logo title, otherwise will use site title
  subtitle = "Matsunaga-lab Saitama University" # Logo subtitle

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "left"  # Configure layout for list pages
  single = false # Configure layout for single pages
  # Enable widgets in given order
  #widgets = ["search", "recent", "categories", "taglist", "social", "languages"]
  #widgets = ["social", "search", "languages"]
  widgets = ["social", "search"]
  # alternatively "ddg-search" can be used, to search via DuckDuckGo
  # widgets = ["ddg-search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget

[Params.widgets.social]
  # Enable parts of social widget
  #facebook = "username"
  #twitter = "username"
  #instagram = "username"
  #linkedin = "username"
  #telegram = "username"
  github = "matsunagalab"
  #gitlab = "username"
  #bitbucket = "username"
  #email = "example@example.com"

[[Menus.main]]
  Name = "Main"
  URL = "/"
  weight = 1

[[Menus.main]]
  Name = "Research"
  URL = "/research/"
  weight = 2

[[Menus.main]]
  Name = "Resources"
  URL = "/resource/"
  weight = 3

[[Menus.main]]
  Name = "Publications"
  URL = "/publication/"
  weight = 4

[[Menus.main]]
  Name = "Members"
  URL = "/member/"
  weight = 5

[[Menus.main]]
  Name = "Teaching"
  URL = "/teaching/"
  weight = 6

[[Menus.main]]
  Name = "学生の皆さんへ"
  URL = "/recruiting/"
  weight = 7

[[Menus.main]]
  Name = "研究室内部向け"
  URL = "/lab/"
  weight = 8

# Custom social links
#[[Params.widgets.social.custom]]
#  title = "Youtube"
#  url = "https://youtube.com/user/username"
#  icon = "youtube.svg" # Optional. Path relative to "layouts/partials"

[[Params.widgets.social.custom]]
  title = "Slack"
  url = "https://w1554361529-tev506983.slack.com"
  icon = "svg/slack.svg"

[[Params.widgets.social.custom]]
  title = "OneDrive"
  url = "https://suitc-my.sharepoint.com/:f:/g/personal/ymatsunaga_mail_saitama-u_ac_jp/Ejkll3xv4iZBmiV49Ns13IIBc9Xoh_aFUODdlF_vIjCq9w"
  icon = "svg/onedrive.svg"

[[Params.widgets.social.custom]]
  title = "OverLeaf"
  url = "https://ja.overleaf.com/project"
  icon = "svg/overleaf.svg"

[[Params.widgets.social.custom]]
  title = "Mendeley"
  url = "https://www.mendeley.com/reference-manager/library/all-references"
  icon = "svg/mendeley.svg"

[[Params.widgets.social.custom]]
  title = "Docker Hub"
  url = "https://hub.docker.com/u/matsunagalab"
  icon = "svg/docker.svg"

[[Params.widgets.social.custom]]
  title = "Google Calendar"
  url = "https://calendar.google.com/calendar"
  icon = "svg/calendar.svg"

[[Params.widgets.social.custom]]
  title = "YouTube"
  url = "https://www.youtube.com/channel/UCO3SW9xZ5DoPOcvdPX7DaFg/videos"
  icon = "svg/youtube.svg"

[[Params.widgets.social.custom]]
  title = "Jupyter on crab"
  url = "http://192.168.1.101:8888/"
  icon = "svg/jupyter.svg"

[[Params.widgets.social.custom]]
  title = "Jupyter on n1"
  url = "http://192.168.1.101:8889/"
  icon = "svg/jupyter.svg"

[[Params.widgets.social.custom]]
  title = "Cluster monitoring"
  url = "http://192.168.1.101:3000/"
  icon = "svg/author.svg"

